import './globals.css'
import { Russo_One, Inter, Varela_Round } from 'next/font/google'
import WalletContextProvider from "./components/WalletContextProvider";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ['latin'] })
const ver = Russo_One({ variable: "--display-font", weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${ver.variable}`}>
      <body className='bg-fuchsia-100' >
        <WalletContextProvider>
          <NavBar />
          {children}
        </WalletContextProvider>
      </body>
    </html>
  )
}
