import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import WalletContextProvider from "./components/WalletContextProvider";
import NavBar from "./components/NavBar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-[#000000]">
        <WalletContextProvider>
          <NavBar />
          {children}
        </WalletContextProvider>
      </body>
    </html>
  )
}
